// packages/svelte/src/components/List.svelte
<script lang="ts">
  interface Props {
    variant?: 'bullet' | 'numbered' | 'none';
    dense?: boolean;
    items?: string[];
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    variant = 'bullet',
    dense = false,
    items,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-list',
      `uds-list--${variant}`,
      dense && 'uds-list--dense',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

{#if variant === 'numbered'}
  <ol class={classes} {...rest}>
    {#if items}
      {#each items as item}
        <li class="uds-list__item">{item}</li>
      {/each}
    {:else}
      {@render children?.()}
    {/if}
  </ol>
{:else}
  <ul class={classes} {...rest}>
    {#if items}
      {#each items as item}
        <li class="uds-list__item">{item}</li>
      {/each}
    {:else}
      {@render children?.()}
    {/if}
  </ul>
{/if}

// packages/react/src/components/List/List.tsx
import React from 'react';

export interface ListProps extends React.HTMLAttributes<HTMLUListElement> {
  variant?: 'bullet' | 'numbered' | 'none';
  dense?: boolean;
  items?: React.ReactNode[];
  children?: React.ReactNode;
}

export const List = React.forwardRef<HTMLUListElement, ListProps>(
  ({ variant = 'bullet', dense = false, items, children, className, ...props }, ref) => {
    const classes = [
      'uds-list',
      `uds-list--${variant}`,
      dense && 'uds-list--dense',
      className,
    ]
      .filter(Boolean)
      .join(' ');
    const content = items != null ? items.map((item, i) => <li key={i} className="uds-list__item">{item}</li>) : children;
    const Tag = variant === 'numbered' ? 'ol' : 'ul';
    return (
      <Tag ref={ref as any} className={classes} {...(props as any)}>
        {content}
      </Tag>
    );
  },
);

List.displayName = 'List';
