// packages/svelte/src/components/Form.svelte
<script lang="ts">
  interface Props {
    id?: string;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let { id, class: className = '', children, ...rest }: Props = $props();

  let classes = $derived(['uds-form', className].filter(Boolean).join(' '));
</script>

<form class={classes} {id} {...rest}>
  {@render children?.()}
</form>

// packages/react/src/components/Form/Form.tsx
import React from 'react';

export interface FormProps extends React.FormHTMLAttributes<HTMLFormElement> {
  /** Optional id for the form (for aria). */
  id?: string;
}

export const Form = React.forwardRef<HTMLFormElement, FormProps>(
  ({ children, className, id, ...props }, ref) => {
    const classes = ['uds-form', className].filter(Boolean).join(' ');
    return (
      <form ref={ref} id={id} className={classes} {...props}>
        {children}
      </form>
    );
  },
);

Form.displayName = 'Form';
