// packages/react/src/components/Avatar/Avatar.tsx
import React from 'react';

export interface AvatarProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'image' | 'initials' | 'icon' | 'group';
  size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
  src?: string;
  alt?: string;
  initials?: string;
  status?: 'online' | 'offline' | 'busy';
  fallback?: React.ReactNode;
}

export const Avatar = React.forwardRef<HTMLDivElement, AvatarProps>(
  ({ variant = 'image', size = 'md', src, alt, initials, status, fallback, className, children, ...props }, ref) => {
    const [imgError, setImgError] = React.useState(false);

    const classes = [
      'uds-avatar',
      `uds-avatar--${variant}`,
      `uds-avatar--${size}`,
      className,
    ].filter(Boolean).join(' ');

    const renderContent = () => {
      if (variant === 'group') return children;
      if (src && !imgError) {
        return <img className="uds-avatar__image" src={src} alt={alt || ''} onError={() => setImgError(true)} />;
      }
      if (initials) {
        return <span className="uds-avatar__initials">{initials}</span>;
      }
      if (fallback) return fallback;
      return <span className="uds-avatar__fallback" aria-hidden="true" />;
    };

    return (
      <div ref={ref} className={classes} aria-label={alt || initials || undefined} {...props}>
        {renderContent()}
        {status && (
          <span className={`uds-avatar__status uds-avatar__status--${status}`} aria-label={status} />
        )}
      </div>
    );
  }
);

Avatar.displayName = 'Avatar';

// packages/svelte/src/components/Avatar.svelte
<script lang="ts">
  interface Props {
    variant?: 'image' | 'initials' | 'icon' | 'group';
    size?: 'xs' | 'sm' | 'md' | 'lg' | 'xl';
    src?: string;
    alt?: string;
    initials?: string;
    status?: 'online' | 'offline' | 'busy';
    fallback?: string;
    class?: string;
    icon?: import('svelte').Snippet;
    children?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    variant = 'image',
    size = 'md',
    src,
    alt = '',
    initials = '',
    status,
    fallback,
    class: className = '',
    icon,
    children,
    ...rest
  }: Props = $props();

  let imgError = $state(false);

  let classes = $derived(
    [
      'uds-avatar',
      `uds-avatar--${variant}`,
      `uds-avatar--${size}`,
      status && `uds-avatar--${status}`,
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

{#if variant === 'group'}
  <div class={classes} role="group" aria-label="User avatars" {...rest}>
    {@render children?.()}
  </div>
{:else}
  <div class={classes} {...rest}>
    {#if variant === 'image' && src && !imgError}
      <img class="uds-avatar__image" src={src} alt={alt} onerror={() => (imgError = true)} />
    {:else if variant === 'icon' && icon}
      <span class="uds-avatar__icon" aria-hidden="true">{@render icon()}</span>
    {:else}
      <span class="uds-avatar__initials" aria-label={alt || initials}>{initials || fallback || '?'}</span>
    {/if}
    {#if status}
      <span class="uds-avatar__status" aria-label={status}></span>
    {/if}
  </div>
{/if}
