// packages/react/src/components/Breadcrumb/Breadcrumb.tsx
import React from 'react';

export interface BreadcrumbItem {
  label: string;
  href?: string;
}

export interface BreadcrumbProps extends React.HTMLAttributes<HTMLElement> {
  items: BreadcrumbItem[];
  separator?: React.ReactNode;
  maxItems?: number;
}

export const Breadcrumb = React.forwardRef<HTMLElement, BreadcrumbProps>(
  ({ items, separator = '/', maxItems, className, ...props }, ref) => {
    const classes = [
      'uds-breadcrumb',
      className,
    ].filter(Boolean).join(' ');

    let displayItems = items;
    const truncated = maxItems && items.length > maxItems;

    if (truncated && maxItems) {
      const head = items.slice(0, 1);
      const tail = items.slice(-(maxItems - 1));
      displayItems = [...head, { label: '...' }, ...tail];
    }

    return (
      <nav ref={ref} className={classes} aria-label="Breadcrumb" {...props}>
        <ol className="uds-breadcrumb__list">
          {displayItems.map((item, index) => {
            const isLast = index === displayItems.length - 1;
            return (
              <li key={index} className="uds-breadcrumb__item">
                {item.href && !isLast ? (
                  <a className="uds-breadcrumb__link" href={item.href}>
                    {item.label}
                  </a>
                ) : (
                  <span
                    className="uds-breadcrumb__text"
                    aria-current={isLast ? 'page' : undefined}
                  >
                    {item.label}
                  </span>
                )}
                {!isLast && (
                  <span className="uds-breadcrumb__separator" aria-hidden="true">
                    {separator}
                  </span>
                )}
              </li>
            );
          })}
        </ol>
      </nav>
    );
  }
);

Breadcrumb.displayName = 'Breadcrumb';

// packages/svelte/src/components/Breadcrumb.svelte
<script lang="ts">
  interface BreadcrumbItem {
    label: string;
    href?: string;
  }

  interface Props {
    variant?: 'standard' | 'truncated';
    items?: BreadcrumbItem[];
    separator?: string;
    maxItems?: number;
    class?: string;
    [key: string]: any;
  }

  let {
    variant = 'standard',
    items = [],
    separator = '/',
    maxItems,
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-breadcrumb',
      `uds-breadcrumb--${variant}`,
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  let displayItems = $derived(() => {
    if (variant === 'truncated' && maxItems && items.length > maxItems) {
      const first = items.slice(0, 1);
      const last = items.slice(-(maxItems - 1));
      return [...first, { label: '...', href: undefined }, ...last];
    }
    return items;
  });
</script>

<nav class={classes} aria-label="Breadcrumb" {...rest}>
  <ol class="uds-breadcrumb__list">
    {#each displayItems() as item, i}
      <li class="uds-breadcrumb__item">
        {#if i > 0}
          <span class="uds-breadcrumb__separator" aria-hidden="true">{separator}</span>
        {/if}
        {#if item.href && i < displayItems().length - 1}
          <a class="uds-breadcrumb__link" href={item.href}>{item.label}</a>
        {:else}
          <span class="uds-breadcrumb__current" aria-current={i === displayItems().length - 1 ? 'page' : undefined}>{item.label}</span>
        {/if}
      </li>
    {/each}
  </ol>
</nav>
