// packages/react/src/components/Checkbox/Checkbox.tsx
import React from 'react';

export interface CheckboxProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'size'> {
  variant?: 'standard' | 'indeterminate';
  label?: string;
  indeterminate?: boolean;
}

export const Checkbox = React.forwardRef<HTMLInputElement, CheckboxProps>(
  ({ variant = 'standard', label, indeterminate, checked, disabled, className, id, name, ...props }, ref) => {
    const inputId = id || (label ? `uds-checkbox-${label.toLowerCase().replace(/\s+/g, '-')}` : undefined);

    const internalRef = React.useCallback(
      (node: HTMLInputElement | null) => {
        if (node) {
          node.indeterminate = !!indeterminate;
        }
        if (typeof ref === 'function') ref(node);
        else if (ref) (ref as React.MutableRefObject<HTMLInputElement | null>).current = node;
      },
      [ref, indeterminate]
    );

    const classes = [
      'uds-checkbox',
      `uds-checkbox--${variant}`,
      indeterminate && 'uds-checkbox--indeterminate',
      className,
    ].filter(Boolean).join(' ');

    return (
      <div className={classes}>
        <input
          ref={internalRef}
          id={inputId}
          type="checkbox"
          className="uds-checkbox__input"
          checked={checked}
          disabled={disabled}
          name={name}
          aria-checked={indeterminate ? 'mixed' : checked}
          {...props}
        />
        {label && (
          <label className="uds-checkbox__label" htmlFor={inputId}>
            {label}
          </label>
        )}
      </div>
    );
  }
);

Checkbox.displayName = 'Checkbox';

// packages/svelte/src/components/Checkbox.svelte
<script lang="ts">
  interface Props {
    checked?: boolean;
    indeterminate?: boolean;
    disabled?: boolean;
    label?: string;
    name?: string;
    value?: string;
    id?: string;
    class?: string;
    [key: string]: any;
  }

  let {
    checked = $bindable(false),
    indeterminate = false,
    disabled = false,
    label = '',
    name,
    value,
    id,
    class: className = '',
    ...rest
  }: Props = $props();

  let checkboxId = $derived(id || `uds-checkbox-${Math.random().toString(36).slice(2, 9)}`);

  let classes = $derived(
    [
      'uds-checkbox',
      indeterminate && 'uds-checkbox--indeterminate',
      disabled && 'uds-checkbox--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  function bindIndeterminate(node: HTMLInputElement) {
    $effect(() => {
      node.indeterminate = indeterminate;
    });
  }
</script>

<div class={classes}>
  <input
    class="uds-checkbox__input"
    type="checkbox"
    id={checkboxId}
    bind:checked
    {disabled}
    {name}
    {value}
    aria-checked={indeterminate ? 'mixed' : checked}
    use:bindIndeterminate
    {...rest}
  />
  {#if label}
    <label class="uds-checkbox__label" for={checkboxId}>{label}</label>
  {/if}
</div>
