// packages/react/src/components/Chip/Chip.tsx
import React from 'react';

export interface ChipProps {
  label: string;
  onRemove?: () => void;
  variant?: 'default' | 'outlined' | 'removable';
  size?: 'sm' | 'md';
  className?: string;
}

export const Chip: React.FC<ChipProps> = ({
  label,
  onRemove,
  variant = 'default',
  size = 'md',
  className,
}) => {
  const classes = [
    'uds-chip',
    `uds-chip--${variant}`,
    `uds-chip--${size}`,
    onRemove && 'uds-chip--removable',
    className,
  ]
    .filter(Boolean)
    .join(' ');
  return (
    <span className={classes} role="listitem">
      <span className="uds-chip__label">{label}</span>
      {onRemove && (
        <button
          type="button"
          className="uds-chip__remove"
          aria-label={`Remove ${label}`}
          onClick={onRemove}
        >
          ×
        </button>
      )}
    </span>
  );
};

Chip.displayName = 'Chip';

// packages/svelte/src/components/Chip.svelte
<script lang="ts">
  interface Props {
    label: string;
    onRemove?: () => void;
    variant?: 'default' | 'outlined' | 'removable';
    size?: 'sm' | 'md';
    class?: string;
    [key: string]: any;
  }

  let {
    label,
    onRemove,
    variant = 'default',
    size = 'md',
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-chip',
      `uds-chip--${variant}`,
      `uds-chip--${size}`,
      onRemove && 'uds-chip--removable',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

<span class={classes} role="listitem" {...rest}>
  <span class="uds-chip__label">{label}</span>
  {#if onRemove}
    <button
      type="button"
      class="uds-chip__remove"
      aria-label={`Remove ${label}`}
      onclick={onRemove}
    >
      &times;
    </button>
  {/if}
</span>
