// packages/react/src/components/CodeBlock/CodeBlock.tsx
import React, { useState, useCallback } from 'react';

export interface CodeBlockTab {
  label: string;
  language: string;
  code: string;
}

export interface CodeBlockProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'syntax-highlighted' | 'terminal' | 'multi-tab';
  size?: 'sm' | 'md' | 'lg';
  language?: string;
  code?: string;
  showLineNumbers?: boolean;
  showCopy?: boolean;
  tabs?: CodeBlockTab[];
}

export const CodeBlock = React.forwardRef<HTMLDivElement, CodeBlockProps>(
  ({ variant = 'syntax-highlighted', size = 'md', language, code, showLineNumbers, showCopy = true, tabs, className, children, ...props }, ref) => {
    const [copied, setCopied] = useState(false);
    const [activeTab, setActiveTab] = useState(0);

    const handleCopy = useCallback(async () => {
      const text = tabs ? tabs[activeTab]?.code : code;
      if (text) {
        await navigator.clipboard.writeText(text);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    }, [code, tabs, activeTab]);

    const classes = [
      'uds-code-block',
      `uds-code-block--${variant}`,
      `uds-code-block--${size}`,
      className,
    ].filter(Boolean).join(' ');

    const activeCode = tabs ? tabs[activeTab]?.code : code;
    const activeLanguage = tabs ? tabs[activeTab]?.language : language;

    const lines = activeCode?.split('\n') || [];

    return (
      <div ref={ref} className={classes} {...props}>
        {tabs && tabs.length > 0 && (
          <div className="uds-code-block__tabs" role="tablist">
            {tabs.map((tab, i) => (
              <button
                key={i}
                className={['uds-code-block__tab', i === activeTab && 'uds-code-block__tab--active'].filter(Boolean).join(' ')}
                role="tab"
                aria-selected={i === activeTab}
                onClick={() => setActiveTab(i)}
                type="button"
              >
                {tab.label}
              </button>
            ))}
          </div>
        )}
        <div className="uds-code-block__header">
          {activeLanguage && <span className="uds-code-block__language">{activeLanguage}</span>}
          {showCopy && (
            <button className="uds-code-block__copy" onClick={handleCopy} aria-label="Copy code" type="button">
              {copied ? 'Copied' : 'Copy'}
            </button>
          )}
        </div>
        <pre className="uds-code-block__pre">
          <code className="uds-code-block__code">
            {showLineNumbers
              ? lines.map((line, i) => (
                  <span key={i} className="uds-code-block__line">
                    <span className="uds-code-block__line-number" aria-hidden="true">{i + 1}</span>
                    {line}
                    {'\n'}
                  </span>
                ))
              : activeCode}
          </code>
        </pre>
        {children}
      </div>
    );
  }
);

CodeBlock.displayName = 'CodeBlock';

// packages/svelte/src/components/CodeBlock.svelte
<script lang="ts">
  interface Tab {
    label: string;
    language: string;
    code: string;
  }

  interface Props {
    variant?: 'syntax-highlighted' | 'terminal' | 'multi-tab';
    size?: 'sm' | 'md' | 'lg';
    language?: string;
    code?: string;
    showLineNumbers?: boolean;
    showCopy?: boolean;
    tabs?: Tab[];
    class?: string;
    [key: string]: any;
  }

  let {
    variant = 'syntax-highlighted',
    size = 'md',
    language = '',
    code = '',
    showLineNumbers = false,
    showCopy = true,
    tabs = [],
    class: className = '',
    ...rest
  }: Props = $props();

  let copied = $state(false);
  let activeTab = $state(0);

  let classes = $derived(
    [
      'uds-code-block',
      `uds-code-block--${variant}`,
      `uds-code-block--${size}`,
      showLineNumbers && 'uds-code-block--line-numbers',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  let displayCode = $derived(
    variant === 'multi-tab' && tabs.length > 0 ? tabs[activeTab].code : code
  );

  let displayLanguage = $derived(
    variant === 'multi-tab' && tabs.length > 0 ? tabs[activeTab].language : language
  );

  async function copyToClipboard() {
    try {
      await navigator.clipboard.writeText(displayCode);
      copied = true;
      setTimeout(() => (copied = false), 2000);
    } catch {
      // Clipboard API not available
    }
  }
</script>

<div class={classes} {...rest}>
  {#if variant === 'multi-tab' && tabs.length > 0}
    <div class="uds-code-block__tabs" role="tablist">
      {#each tabs as tab, i}
        <button
          class="uds-code-block__tab"
          class:uds-code-block__tab--active={i === activeTab}
          role="tab"
          aria-selected={i === activeTab}
          onclick={() => (activeTab = i)}
        >
          {tab.label}
        </button>
      {/each}
    </div>
  {/if}
  <div class="uds-code-block__container">
    {#if showCopy}
      <button class="uds-code-block__copy" onclick={copyToClipboard} aria-label="Copy code">
        {copied ? 'Copied' : 'Copy'}
      </button>
    {/if}
    <pre class="uds-code-block__pre"><code class="uds-code-block__code language-{displayLanguage}">{displayCode}</code></pre>
  </div>
</div>
