// packages/react/src/components/CommandPalette/CommandPalette.tsx
import React, { useState, useCallback, useRef, useEffect, useId } from 'react';

export interface CommandPaletteAction {
  id: string;
  label: string;
  group?: string;
  icon?: React.ReactNode;
  shortcut?: string;
  disabled?: boolean;
}

export interface CommandPaletteGroup {
  label: string;
  id: string;
}

export interface CommandPaletteProps extends React.HTMLAttributes<HTMLDivElement> {
  open: boolean;
  onClose: () => void;
  size?: 'md' | 'lg';
  actions: CommandPaletteAction[];
  groups?: CommandPaletteGroup[];
  onSelect: (actionId: string) => void;
  placeholder?: string;
  recentLimit?: number;
}

export const CommandPalette = React.forwardRef<HTMLDivElement, CommandPaletteProps>(
  ({ open, onClose, size = 'md', actions, groups, onSelect, placeholder = 'Type a command...', recentLimit, className, ...props }, ref) => {
    const [query, setQuery] = useState('');
    const [activeIndex, setActiveIndex] = useState(0);
    const inputRef = useRef<HTMLInputElement>(null);
    const listboxId = useId();

    const filtered = actions.filter(
      (a) => a.label.toLowerCase().includes(query.toLowerCase())
    );

    useEffect(() => {
      if (open) {
        setQuery('');
        setActiveIndex(0);
        requestAnimationFrame(() => inputRef.current?.focus());
      }
    }, [open]);

    useEffect(() => {
      if (!open) return;
      const handleKeyDown = (e: KeyboardEvent) => {
        if (e.key === 'Escape') {
          e.preventDefault();
          onClose();
        }
      };
      document.addEventListener('keydown', handleKeyDown);
      return () => document.removeEventListener('keydown', handleKeyDown);
    }, [open, onClose]);

    const handleKeyDown = useCallback(
      (e: React.KeyboardEvent) => {
        if (e.key === 'ArrowDown') {
          e.preventDefault();
          setActiveIndex((prev) => Math.min(prev + 1, filtered.length - 1));
        } else if (e.key === 'ArrowUp') {
          e.preventDefault();
          setActiveIndex((prev) => Math.max(prev - 1, 0));
        } else if (e.key === 'Enter') {
          e.preventDefault();
          const item = filtered[activeIndex];
          if (item && !item.disabled) {
            onSelect(item.id);
            onClose();
          }
        }
      },
      [filtered, activeIndex, onSelect, onClose]
    );

    if (!open) return null;

    const classes = [
      'uds-command-palette',
      `uds-command-palette--${size}`,
      className,
    ].filter(Boolean).join(' ');

    const groupedActions = groups
      ? groups.map((g) => ({
          ...g,
          actions: filtered.filter((a) => a.group === g.id),
        }))
      : [{ id: 'all', label: '', actions: filtered }];

    return (
      <div className="uds-command-palette-overlay" onClick={(e) => { if (e.target === e.currentTarget) onClose(); }} role="presentation">
        <div ref={ref} className={classes} role="combobox" aria-expanded="true" aria-haspopup="listbox" aria-owns={listboxId} {...props}>
          <div className="uds-command-palette__input-wrapper">
            <input
              ref={inputRef}
              className="uds-command-palette__input"
              type="text"
              value={query}
              onChange={(e) => { setQuery(e.target.value); setActiveIndex(0); }}
              onKeyDown={handleKeyDown}
              placeholder={placeholder}
              role="searchbox"
              aria-autocomplete="list"
              aria-controls={listboxId}
              aria-activedescendant={filtered[activeIndex] ? `cmd-${filtered[activeIndex].id}` : undefined}
            />
          </div>
          <div id={listboxId} className="uds-command-palette__list" role="listbox">
            {groupedActions.map((group) => (
              <div key={group.id} className="uds-command-palette__group">
                {group.label && <div className="uds-command-palette__group-label">{group.label}</div>}
                {group.actions.map((action, i) => {
                  const globalIndex = filtered.indexOf(action);
                  return (
                    <div
                      key={action.id}
                      id={`cmd-${action.id}`}
                      className={[
                        'uds-command-palette__item',
                        globalIndex === activeIndex && 'uds-command-palette__item--active',
                        action.disabled && 'uds-command-palette__item--disabled',
                      ].filter(Boolean).join(' ')}
                      role="option"
                      aria-selected={globalIndex === activeIndex}
                      aria-disabled={action.disabled}
                      onClick={() => {
                        if (!action.disabled) {
                          onSelect(action.id);
                          onClose();
                        }
                      }}
                    >
                      {action.icon && <span className="uds-command-palette__item-icon">{action.icon}</span>}
                      <span className="uds-command-palette__item-label">{action.label}</span>
                      {action.shortcut && <kbd className="uds-command-palette__item-shortcut">{action.shortcut}</kbd>}
                    </div>
                  );
                })}
              </div>
            ))}
            {filtered.length === 0 && (
              <div className="uds-command-palette__empty">No results found</div>
            )}
          </div>
        </div>
      </div>
    );
  }
);

CommandPalette.displayName = 'CommandPalette';

// packages/svelte/src/components/CommandPalette.svelte
<script lang="ts">
  interface CommandAction {
    id: string;
    label: string;
    group?: string;
    shortcut?: string;
    icon?: string;
  }

  interface Props {
    open?: boolean;
    actions?: CommandAction[];
    groups?: string[];
    placeholder?: string;
    recentLimit?: number;
    onSelect?: (actionId: string) => void;
    onClose?: () => void;
    class?: string;
    [key: string]: any;
  }

  let {
    open = false,
    actions = [],
    groups = [],
    placeholder = 'Type a command...',
    recentLimit = 5,
    onSelect,
    onClose,
    class: className = '',
    ...rest
  }: Props = $props();

  let query = $state('');
  let activeIndex = $state(0);

  let classes = $derived(
    [
      'uds-command-palette',
      open && 'uds-command-palette--open',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  let filteredActions = $derived(
    query
      ? actions.filter((a) => a.label.toLowerCase().includes(query.toLowerCase()))
      : actions.slice(0, recentLimit)
  );

  let groupedActions = $derived(() => {
    if (groups.length === 0) return [{ group: '', actions: filteredActions }];
    const grouped: { group: string; actions: CommandAction[] }[] = [];
    for (const group of groups) {
      const items = filteredActions.filter((a) => a.group === group);
      if (items.length > 0) grouped.push({ group, actions: items });
    }
    const ungrouped = filteredActions.filter((a) => !a.group || !groups.includes(a.group));
    if (ungrouped.length > 0) grouped.push({ group: '', actions: ungrouped });
    return grouped;
  });

  function handleSelect(action: CommandAction) {
    onSelect?.(action.id);
    query = '';
  }

  function handleKeydown(event: KeyboardEvent) {
    if (event.key === 'ArrowDown') {
      event.preventDefault();
      activeIndex = Math.min(activeIndex + 1, filteredActions.length - 1);
    } else if (event.key === 'ArrowUp') {
      event.preventDefault();
      activeIndex = Math.max(activeIndex - 1, 0);
    } else if (event.key === 'Enter' && filteredActions[activeIndex]) {
      event.preventDefault();
      handleSelect(filteredActions[activeIndex]);
    } else if (event.key === 'Escape') {
      event.preventDefault();
      onClose?.();
    }
  }

  $effect(() => {
    activeIndex = 0;
  });
</script>

{#if open}
  <div class="uds-command-palette__overlay" onclick={onClose} aria-hidden="true"></div>
  <div class={classes} role="dialog" aria-label="Command palette" {...rest}>
    <div class="uds-command-palette__input-wrapper">
      <input
        class="uds-command-palette__input"
        type="text"
        bind:value={query}
        {placeholder}
        role="combobox"
        aria-expanded="true"
        aria-controls="command-palette-list"
        aria-activedescendant={filteredActions[activeIndex] ? `command-${filteredActions[activeIndex].id}` : undefined}
        onkeydown={handleKeydown}
      />
    </div>
    <ul class="uds-command-palette__list" id="command-palette-list" role="listbox">
      {#each groupedActions() as group}
        {#if group.group}
          <li class="uds-command-palette__group-label" role="presentation">{group.group}</li>
        {/if}
        {#each group.actions as action, i}
          <li
            class="uds-command-palette__item"
            class:uds-command-palette__item--active={filteredActions.indexOf(action) === activeIndex}
            id="command-{action.id}"
            role="option"
            aria-selected={filteredActions.indexOf(action) === activeIndex}
            onclick={() => handleSelect(action)}
          >
            <span class="uds-command-palette__item-label">{action.label}</span>
            {#if action.shortcut}
              <kbd class="uds-command-palette__shortcut">{action.shortcut}</kbd>
            {/if}
          </li>
        {/each}
      {/each}
      {#if filteredActions.length === 0}
        <li class="uds-command-palette__empty" role="presentation">No results found</li>
      {/if}
    </ul>
  </div>
{/if}
