// packages/react/src/components/ContextMenu/ContextMenu.tsx
import React from 'react';
import ReactDOM from 'react-dom';

export interface ContextMenuItem {
  id: string;
  label: string;
  disabled?: boolean;
}

export interface ContextMenuProps {
  items: ContextMenuItem[];
  onSelect?: (id: string) => void;
  children: React.ReactNode;
  className?: string;
}

export const ContextMenu: React.FC<ContextMenuProps> = ({
  items,
  onSelect,
  children,
  className,
}) => {
  const [open, setOpen] = React.useState(false);
  const [pos, setPos] = React.useState({ x: 0, y: 0 });
  const ref = React.useRef<HTMLDivElement>(null);

  const handleContextMenu = (e: React.MouseEvent) => {
    e.preventDefault();
    setPos({ x: e.clientX, y: e.clientY });
    setOpen(true);
  };

  React.useEffect(() => {
    if (!open) return;
    const close = () => setOpen(false);
    document.addEventListener('click', close);
    document.addEventListener('scroll', close, true);
    return () => {
      document.removeEventListener('click', close);
      document.removeEventListener('scroll', close, true);
    };
  }, [open]);

  const classes = ['uds-context-menu', className].filter(Boolean).join(' ');
  return (
    <section
      ref={ref}
      className={classes}
      aria-label="Context menu trigger"
      onContextMenu={handleContextMenu}
    >
      {children}
      {open &&
        ReactDOM.createPortal(
          <div
            className="uds-context-menu__menu"
            role="menu"
            tabIndex={-1}
            style={{ left: pos.x, top: pos.y }}
            onClick={(e) => e.stopPropagation()}
            onKeyDown={(e) => e.stopPropagation()}
          >
            {items.map((item) => (
              <button
                key={item.id}
                type="button"
                role="menuitem"
                className="uds-context-menu__item"
                disabled={item.disabled}
                onClick={() => {
                  onSelect?.(item.id);
                  setOpen(false);
                }}
              >
                {item.label}
              </button>
            ))}
          </div>,
          document.body,
        )}
    </section>
  );
};

ContextMenu.displayName = 'ContextMenu';

// packages/svelte/src/components/ContextMenu.svelte
<script lang="ts">
  interface ContextMenuItem {
    id: string;
    label: string;
    disabled?: boolean;
  }

  interface Props {
    items: ContextMenuItem[];
    onSelect?: (id: string) => void;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    items,
    onSelect,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let open = $state(false);
  let pos = $state({ x: 0, y: 0 });

  let classes = $derived(
    ['uds-context-menu', className].filter(Boolean).join(' ')
  );

  function handleContextMenu(event: MouseEvent) {
    event.preventDefault();
    pos = { x: event.clientX, y: event.clientY };
    open = true;
  }

  function selectItem(item: ContextMenuItem) {
    if (!item.disabled) {
      onSelect?.(item.id);
      open = false;
    }
  }

  $effect(() => {
    if (!open) return;
    function close() {
      open = false;
    }
    document.addEventListener('click', close);
    document.addEventListener('scroll', close, true);
    return () => {
      document.removeEventListener('click', close);
      document.removeEventListener('scroll', close, true);
    };
  });
</script>

<div
  class={classes}
  role="region"
  aria-label="Context menu trigger"
  oncontextmenu={handleContextMenu}
  {...rest}
>
  {@render children?.()}
  {#if open}
    <svelte:portal target="body">
      <div
        class="uds-context-menu__menu"
        role="menu"
        style:position="fixed"
        style:left="{pos.x}px"
        style:top="{pos.y}px"
        onclick={(e) => e.stopPropagation()}
        onkeydown={(e) => e.stopPropagation()}
      >
        {#each items as item (item.id)}
          <button
            type="button"
            role="menuitem"
            class="uds-context-menu__item"
            disabled={item.disabled}
            onclick={() => selectItem(item)}
          >
            {item.label}
          </button>
        {/each}
      </div>
    </svelte:portal>
  {/if}
</div>
