// packages/react/src/components/Descriptions/Descriptions.tsx
import React from 'react';

export interface DescriptionsItem {
  label: React.ReactNode;
  value: React.ReactNode;
}

export interface DescriptionsProps {
  items: DescriptionsItem[];
  layout?: 'horizontal' | 'vertical' | 'bordered';
  className?: string;
}

export const Descriptions: React.FC<DescriptionsProps> = ({
  items,
  layout = 'horizontal',
  className,
}) => {
  const classes = ['uds-descriptions', `uds-descriptions--${layout}`, className].filter(Boolean).join(' ');
  return (
    <dl className={classes}>
      {items.map((item, i) => (
        <React.Fragment key={i}>
          <dt className="uds-descriptions__label">{item.label}</dt>
          <dd className="uds-descriptions__value">{item.value}</dd>
        </React.Fragment>
      ))}
    </dl>
  );
};

Descriptions.displayName = 'Descriptions';

// packages/svelte/src/components/Descriptions.svelte
<script lang="ts">
  interface DescriptionsItem {
    label: string;
    value: string;
  }

  interface Props {
    items: DescriptionsItem[];
    layout?: 'horizontal' | 'vertical' | 'bordered';
    class?: string;
    [key: string]: any;
  }

  let {
    items,
    layout = 'horizontal',
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-descriptions', `uds-descriptions--${layout}`, className]
      .filter(Boolean)
      .join(' ')
  );
</script>

<dl class={classes} {...rest}>
  {#each items as item (item.label)}
    <dt class="uds-descriptions__label">{item.label}</dt>
    <dd class="uds-descriptions__value">{item.value}</dd>
  {/each}
</dl>
