// packages/react/src/components/Divider/Divider.tsx
import React from 'react';

export interface DividerProps extends React.HTMLAttributes<HTMLHRElement> {
  /** Orientation. @default 'horizontal' */
  orientation?: 'horizontal' | 'vertical';
  /** Visual variant. @default 'line' */
  variant?: 'line' | 'dashed';
}

export const Divider = React.forwardRef<HTMLHRElement, DividerProps>(
  ({ orientation = 'horizontal', variant = 'line', className, ...props }, ref) => {
    const classes = [
      'uds-divider',
      `uds-divider--${orientation}`,
      variant === 'dashed' && 'uds-divider--dashed',
      className,
    ]
      .filter(Boolean)
      .join(' ');
    return <hr ref={ref} className={classes} role="separator" {...props} />;
  },
);

Divider.displayName = 'Divider';

// packages/svelte/src/components/Divider.svelte
<script lang="ts">
  interface Props {
    orientation?: 'horizontal' | 'vertical';
    variant?: 'line' | 'dashed';
    class?: string;
    [key: string]: unknown;
  }

  let {
    orientation = 'horizontal',
    variant = 'line',
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-divider',
      `uds-divider--${orientation}`,
      variant === 'dashed' && 'uds-divider--dashed',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

<hr class={classes} role="separator" {...rest} />
