// packages/react/src/components/Empty/Empty.tsx
import type React from 'react';

export interface EmptyProps {
  title?: string;
  description?: string;
  illustration?: React.ReactNode;
  action?: React.ReactNode;
  className?: string;
}

export const Empty: React.FC<EmptyProps> = ({
  title = 'No data',
  description,
  illustration,
  action,
  className,
}) => {
  const classes = ['uds-empty', className].filter(Boolean).join(' ');
  return (
    <output className={classes} aria-label={title} htmlFor="">
      {illustration && <div className="uds-empty__illustration">{illustration}</div>}
      <h3 className="uds-empty__title">{title}</h3>
      {description && <p className="uds-empty__description">{description}</p>}
      {action && <div className="uds-empty__action">{action}</div>}
    </output>
  );
};

Empty.displayName = 'Empty';

// packages/svelte/src/components/Empty.svelte
<script lang="ts">
  interface Props {
    title?: string;
    description?: string;
    class?: string;
    illustration?: import('svelte').Snippet;
    action?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    title = 'No data',
    description,
    class: className = '',
    illustration,
    action,
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-empty', className].filter(Boolean).join(' ')
  );
</script>

<output class={classes} aria-label={title} for="" {...rest}>
  {#if illustration}
    <div class="uds-empty__illustration">{@render illustration()}</div>
  {/if}
  <h3 class="uds-empty__title">{title}</h3>
  {#if description}
    <p class="uds-empty__description">{description}</p>
  {/if}
  {#if action}
    <div class="uds-empty__action">{@render action()}</div>
  {/if}
</output>
