// packages/react/src/components/FileUpload/FileUpload.tsx
import React, { useCallback, useRef, useState } from 'react';

/**
 * Props for the {@link FileUpload} component.
 *
 * Extends native `<div>` attributes (with `onDrop` replaced).
 */
export interface FileUploadProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'onDrop'> {
  /** Upload interaction style. @default 'dropzone' */
  variant?: 'dropzone' | 'button' | 'avatar-upload';
  /** Controls the zone dimensions. @default 'md' */
  size?: 'sm' | 'md' | 'lg';
  /** Accepted file types (MIME types or extensions, e.g. ".png,.jpg"). */
  accept?: string;
  /** Maximum file size in bytes. */
  maxSize?: number;
  /** Maximum number of files that can be uploaded. */
  maxFiles?: number;
  /** Allow selecting multiple files at once. */
  multiple?: boolean;
  /** Called with the validated files when new files are added. */
  onUpload?: (files: File[]) => void;
  /** Called when a file is removed from the list. */
  onRemove?: (file: File) => void;
  /** Disables the upload zone. */
  disabled?: boolean;
  /** Accessible label for the upload zone. @default 'Upload files' */
  label?: string;
  /** Error message shown below the zone (e.g. validation from parent). Overrides internal validation error when set. */
  error?: string;
  /** Main placeholder text when no custom children. @default 'Drag and drop files here, or click to browse' (dropzone) or 'Choose file' (button) */
  placeholderTitle?: string;
  /** Optional second line in placeholder (e.g. accepted types or size limit). */
  placeholderDescription?: string;
  /** Label for the browse action in placeholder. @default 'browse' */
  acceptLabel?: string;
}

/**
 * A file upload zone supporting drag-and-drop and click-to-browse,
 * with built-in file-size and file-count validation.
 *
 * Displays an uploaded file list with remove buttons.
 * Uses `role="button"` on the drop zone for keyboard accessibility,
 * and `role="alert"` / `aria-live` for error and file-list updates.
 *
 * Uses BEM class `uds-file-upload` with variant, size, drag-over,
 * and disabled modifiers.
 * Forwards its ref to the root `<div>` element.
 *
 * @example
 * ```tsx
 * <FileUpload
 *   accept=".png,.jpg"
 *   maxSize={5 * 1024 * 1024}
 *   onUpload={(files) => upload(files)}
 * />
 * ```
 */
export const FileUpload = React.forwardRef<HTMLDivElement, FileUploadProps>(
  (
    {
      variant = 'dropzone',
      size = 'md',
      accept,
      maxSize,
      maxFiles,
      multiple,
      onUpload,
      onRemove,
      disabled,
      label,
      error: errorProp,
      placeholderTitle,
      placeholderDescription,
      acceptLabel = 'browse',
      className,
      children,
      ...props
    },
    ref,
  ) => {
    const [dragOver, setDragOver] = useState(false);
    const [files, setFiles] = useState<File[]>([]);
    const [internalError, setInternalError] = useState<string | null>(null);
    const error = errorProp ?? internalError;
    const inputRef = useRef<HTMLInputElement>(null);

    const validateFiles = useCallback(
      (incoming: File[]): File[] => {
        setInternalError(null);
        let valid = incoming;
        if (maxSize) {
          const oversized = valid.filter((f) => f.size > maxSize);
          if (oversized.length > 0) {
            setInternalError(`File too large: ${oversized[0].name}`);
            valid = valid.filter((f) => f.size <= maxSize);
          }
        }
        if (maxFiles) {
          valid = valid.slice(0, maxFiles - files.length);
        }
        return valid;
      },
      [maxSize, maxFiles, files.length],
    );

    const handleFiles = useCallback(
      (incoming: File[]) => {
        const valid = validateFiles(incoming);
        if (valid.length > 0) {
          setFiles((prev) => [...prev, ...valid]);
          onUpload?.(valid);
        }
      },
      [validateFiles, onUpload],
    );

    const handleDrop = useCallback(
      (e: React.DragEvent) => {
        e.preventDefault();
        setDragOver(false);
        if (disabled) return;
        const dropped = Array.from(e.dataTransfer.files);
        handleFiles(dropped);
      },
      [disabled, handleFiles],
    );

    const handleChange = useCallback(
      (e: React.ChangeEvent<HTMLInputElement>) => {
        if (e.target.files) {
          handleFiles(Array.from(e.target.files));
        }
      },
      [handleFiles],
    );

    const handleRemove = useCallback(
      (file: File) => {
        setFiles((prev) => prev.filter((f) => f !== file));
        onRemove?.(file);
      },
      [onRemove],
    );

    const classes = [
      'uds-file-upload',
      `uds-file-upload--${variant}`,
      `uds-file-upload--${size}`,
      dragOver && 'uds-file-upload--drag-over',
      disabled && 'uds-file-upload--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ');

    return (
      <div ref={ref} className={classes} {...props}>
        <button
          className="uds-file-upload__zone"
          type="button"
          tabIndex={disabled ? -1 : 0}
          aria-label={label || 'Upload files'}
          disabled={disabled}
          onDragOver={(e) => {
            e.preventDefault();
            if (!disabled) setDragOver(true);
          }}
          onDragLeave={() => setDragOver(false)}
          onDrop={handleDrop}
          onClick={() => !disabled && inputRef.current?.click()}
          onKeyDown={(e) => {
            if ((e.key === 'Enter' || e.key === ' ') && !disabled) {
              e.preventDefault();
              inputRef.current?.click();
            }
          }}
        >
          <input
            ref={inputRef}
            type="file"
            className="uds-file-upload__input"
            accept={accept}
            multiple={multiple}
            onChange={handleChange}
            aria-label={label || 'Upload files'}
            hidden
          />
          {children ?? (
            <div className="uds-file-upload__placeholder">
              <p className="uds-file-upload__text">
                {placeholderTitle ??
                  (variant === 'button'
                    ? 'Choose file'
                    : `Drag and drop files here, or click to ${acceptLabel}`)}
              </p>
              {placeholderDescription && (
                <p className="uds-file-upload__sub">{placeholderDescription}</p>
              )}
            </div>
          )}
        </button>
        {error && (
          <p className="uds-file-upload__error" role="alert" aria-live="polite">
            {error}
          </p>
        )}
        {files.length > 0 && (
          <ul className="uds-file-upload__list" aria-live="polite">
            {files.map((file) => (
              <li key={file.name} className="uds-file-upload__file">
                <span className="uds-file-upload__file-name">{file.name}</span>
                <button
                  className="uds-file-upload__file-remove"
                  onClick={() => handleRemove(file)}
                  aria-label={`Remove ${file.name}`}
                  type="button"
                >
                  Remove
                </button>
              </li>
            ))}
          </ul>
        )}
      </div>
    );
  },
);

FileUpload.displayName = 'FileUpload';

// packages/svelte/src/components/FileUpload.svelte
<script lang="ts">
  interface Props {
    variant?: 'dropzone' | 'button' | 'avatar-upload';
    size?: 'sm' | 'md' | 'lg';
    accept?: string;
    maxSize?: number;
    maxFiles?: number;
    multiple?: boolean;
    disabled?: boolean;
    /** Accessible label for the upload zone. @default 'Upload files' */
    label?: string;
    /** Error message shown below the zone (e.g. validation from parent). Overrides internal error. */
    error?: string;
    /** Main placeholder text when no custom children. */
    placeholderTitle?: string;
    /** Optional second line in placeholder (e.g. accepted types or size limit). */
    placeholderDescription?: string;
    /** Label for the browse action in placeholder. @default 'browse' */
    acceptLabel?: string;
    onUpload?: (files: File[]) => void;
    onRemove?: (file: File) => void;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    variant = 'dropzone',
    size = 'md',
    accept,
    maxSize,
    maxFiles = 1,
    multiple = false,
    disabled = false,
    label = 'Upload files',
    error: errorProp,
    placeholderTitle,
    placeholderDescription,
    acceptLabel = 'browse',
    onUpload,
    onRemove,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let dragOver = $state(false);
  let internalError = $state<string | null>(null);
  let inputId = $derived(`uds-file-upload-${Math.random().toString(36).slice(2, 9)}`);

  let displayError = $derived(errorProp ?? internalError);

  let classes = $derived(
    [
      'uds-file-upload',
      `uds-file-upload--${variant}`,
      `uds-file-upload--${size}`,
      dragOver && 'uds-file-upload--drag-over',
      disabled && 'uds-file-upload--disabled',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  let placeholderText = $derived(
    placeholderTitle ??
      (variant === 'button'
        ? 'Choose file'
        : `Drag and drop files here, or click to ${acceptLabel}`)
  );

  function validateFiles(files: File[]): File[] {
    internalError = null;
    let valid = files;
    if (maxSize) {
      const oversized = valid.filter((f) => f.size > maxSize!);
      if (oversized.length > 0) {
        internalError = `File too large: ${oversized[0].name}`;
        valid = valid.filter((f) => f.size <= maxSize!);
      }
    }
    if (maxFiles) {
      valid = valid.slice(0, maxFiles);
    }
    return valid;
  }

  function handleFiles(fileList: FileList | null) {
    if (!fileList) return;
    const files = Array.from(fileList);
    const valid = validateFiles(files);
    if (valid.length) {
      onUpload?.(valid);
    }
  }

  function handleFileChange(event: Event) {
    const target = event.target as HTMLInputElement;
    handleFiles(target.files);
    target.value = '';
  }

  function handleDrop(event: DragEvent) {
    event.preventDefault();
    dragOver = false;
    if (disabled) return;
    handleFiles(event.dataTransfer?.files || null);
  }

  function handleDragOver(event: DragEvent) {
    event.preventDefault();
    if (!disabled) dragOver = true;
  }

  function handleDragLeave() {
    dragOver = false;
  }

  function openFileDialog() {
    document.getElementById(inputId)?.click();
  }
</script>

<div class={classes} {...rest}>
  <input
    class="uds-file-upload__input"
    type="file"
    id={inputId}
    {accept}
    {multiple}
    {disabled}
    aria-label={label}
    onchange={handleFileChange}
    hidden
  />

  {#if variant === 'dropzone'}
    <button
      type="button"
      class="uds-file-upload__zone"
      aria-label={label}
      aria-disabled={disabled || undefined}
      ondrop={handleDrop}
      ondragover={handleDragOver}
      ondragleave={handleDragLeave}
      onclick={openFileDialog}
    >
      {#if children}
        {@render children()}
      {:else}
        <div class="uds-file-upload__placeholder">
          <p class="uds-file-upload__text">{placeholderText}</p>
          {#if placeholderDescription}
            <p class="uds-file-upload__sub">{placeholderDescription}</p>
          {/if}
        </div>
      {/if}
    </button>
  {:else if variant === 'button'}
    <button
      type="button"
      class="uds-file-upload__zone uds-file-upload__zone--button"
      {disabled}
      onclick={openFileDialog}
    >
      {#if children}
        {@render children()}
      {:else}
        {placeholderText}
      {/if}
    </button>
  {:else if variant === 'avatar-upload'}
    <button
      type="button"
      class="uds-file-upload__zone uds-file-upload__zone--avatar"
      aria-disabled={disabled || undefined}
      onclick={openFileDialog}
    >
      {#if children}
        {@render children()}
      {:else}
        <span class="uds-file-upload__avatar-placeholder" aria-hidden="true">+</span>
      {/if}
    </button>
  {/if}

  {#if displayError}
    <p class="uds-file-upload__error" role="alert">{displayError}</p>
  {/if}
</div>
