// packages/react/src/components/Footer/Footer.tsx
import React from 'react';

export interface FooterColumn {
  title: string;
  links: { label: string; href: string }[];
}

export interface FooterProps extends React.HTMLAttributes<HTMLElement> {
  variant?: 'simple' | 'multi-column' | 'newsletter' | 'mega-footer';
  size?: 'standard' | 'compact';
  columns?: FooterColumn[];
  newsletter?: React.ReactNode;
  legal?: React.ReactNode;
  copyright?: string;
}

export const Footer = React.forwardRef<HTMLElement, FooterProps>(
  ({ variant = 'simple', size = 'standard', columns, newsletter, legal, copyright, className, children, ...props }, ref) => {
    const classes = [
      'uds-footer',
      `uds-footer--${variant}`,
      `uds-footer--${size}`,
      className,
    ].filter(Boolean).join(' ');

    return (
      <footer ref={ref} className={classes} aria-label="Site footer" {...props}>
        {columns && columns.length > 0 && (
          <div className="uds-footer__columns">
            {columns.map((col, i) => (
              <div key={i} className="uds-footer__column">
                <h3 className="uds-footer__column-title">{col.title}</h3>
                <ul className="uds-footer__links">
                  {col.links.map((link, j) => (
                    <li key={j}><a href={link.href} className="uds-footer__link">{link.label}</a></li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        )}
        {newsletter && <div className="uds-footer__newsletter">{newsletter}</div>}
        {children}
        {legal && <div className="uds-footer__legal">{legal}</div>}
        {copyright && <p className="uds-footer__copyright">{copyright}</p>}
      </footer>
    );
  }
);

Footer.displayName = 'Footer';

// packages/svelte/src/components/Footer.svelte
<script lang="ts">
  interface FooterColumn {
    title: string;
    links: { label: string; href: string }[];
  }

  interface Props {
    variant?: 'simple' | 'multi-column' | 'newsletter' | 'mega-footer';
    size?: 'standard' | 'compact';
    columns?: FooterColumn[];
    copyright?: string;
    class?: string;
    children?: import('svelte').Snippet;
    newsletter?: import('svelte').Snippet;
    legal?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    variant = 'simple',
    size = 'standard',
    columns = [],
    copyright = '',
    class: className = '',
    children,
    newsletter,
    legal,
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-footer',
      `uds-footer--${variant}`,
      `uds-footer--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

<footer class={classes} aria-label="Site footer" {...rest}>
  {#if columns.length > 0}
    <div class="uds-footer__columns">
      {#each columns as column}
        <div class="uds-footer__column">
          <h3 class="uds-footer__column-title">{column.title}</h3>
          <ul class="uds-footer__link-list">
            {#each column.links as link}
              <li><a href={link.href}>{link.label}</a></li>
            {/each}
          </ul>
        </div>
      {/each}
    </div>
  {/if}
  {#if newsletter}
    <div class="uds-footer__newsletter">
      {@render newsletter()}
    </div>
  {/if}
  {@render children?.()}
  {#if legal}
    <div class="uds-footer__legal">
      {@render legal()}
    </div>
  {/if}
  {#if copyright}
    <div class="uds-footer__copyright">{copyright}</div>
  {/if}
</footer>
