// packages/react/src/components/Link/Link.tsx
import React from 'react';

export interface LinkProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  /** Visual variant. @default 'primary' */
  variant?: 'default' | 'muted' | 'primary';
  /** When true, adds rel and target for external links. */
  external?: boolean;
}

export const Link = React.forwardRef<HTMLAnchorElement, LinkProps>(
  ({ variant = 'primary', external, href, className, children, ...props }, ref) => {
    const classes = ['uds-link', `uds-link--${variant}`, className].filter(Boolean).join(' ');
    const rel = external ? 'noopener noreferrer' : undefined;
    const target = external ? '_blank' : undefined;
    return (
      <a ref={ref} href={href} className={classes} rel={rel} target={target} {...props}>
        {children}
      </a>
    );
  },
);

Link.displayName = 'Link';

// packages/svelte/src/components/Link.svelte
<script lang="ts">
  interface Props {
    href: string;
    variant?: 'default' | 'muted' | 'primary';
    external?: boolean;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let {
    href,
    variant = 'primary',
    external = false,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let classes = $derived(['uds-link', `uds-link--${variant}`, className].filter(Boolean).join(' '));
  let rel = $derived(external ? 'noopener noreferrer' : undefined);
  let target = $derived(external ? '_blank' : undefined);
</script>

<a class={classes} {href} {rel} {target} {...rest}>
  {@render children?.()}
</a>
