// packages/react/src/components/Rating/Rating.tsx
import React from 'react';

export interface RatingProps {
  value?: number;
  max?: number;
  onChange?: (value: number) => void;
  disabled?: boolean;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export const Rating: React.FC<RatingProps> = ({
  value = 0,
  max = 5,
  onChange,
  disabled = false,
  size = 'md',
  className,
}) => {
  const classes = ['uds-rating', `uds-rating--${size}`, className].filter(Boolean).join(' ');
  return (
    <div
      className={classes}
      role="group"
      aria-label={`Rating ${value} of ${max}`}
    >
      {Array.from({ length: max }, (_, i) => {
        const starValue = i + 1;
        const filled = value >= starValue;
        return (
          <button
            key={i}
            type="button"
            className={`uds-rating__star ${filled ? 'uds-rating__star--filled' : ''}`}
            aria-label={`${starValue} star${starValue > 1 ? 's' : ''}`}
            disabled={disabled}
            onClick={() => onChange?.(starValue)}
          >
            <span aria-hidden="true">{filled ? '★' : '☆'}</span>
          </button>
        );
      })}
    </div>
  );
};

Rating.displayName = 'Rating';

// packages/svelte/src/components/Rating.svelte
<script lang="ts">
  interface Props {
    value?: number;
    max?: number;
    size?: 'sm' | 'md' | 'lg';
    disabled?: boolean;
    onChange?: (v: number) => void;
    class?: string;
    [key: string]: unknown;
  }

  let {
    value = 0,
    max = 5,
    size = 'md',
    disabled = false,
    onChange,
    class: className = '',
  }: Props = $props();

  let classes = $derived(['uds-rating', `uds-rating--${size}`, className].filter(Boolean).join(' '));
</script>

<div class={classes} role="group" aria-label="Rating {value} of {max}">
  {#each Array(max) as _, i}
    {@const starValue = i + 1}
    <button
      type="button"
      class="uds-rating__star"
      class:uds-rating__star--filled={value >= starValue}
      aria-label="{starValue} star{starValue > 1 ? 's' : ''}"
      {disabled}
      onclick={() => onChange?.(starValue)}
    >
      <span aria-hidden="true">{value >= starValue ? '★' : '☆'}</span>
    </button>
  {/each}
</div>
