// packages/react/src/components/Statistic/Statistic.tsx
import type React from 'react';

export interface StatisticProps {
  value: React.ReactNode;
  label?: string;
  prefix?: React.ReactNode;
  suffix?: React.ReactNode;
  size?: 'sm' | 'md' | 'lg';
  className?: string;
}

export const Statistic: React.FC<StatisticProps> = ({
  value,
  label,
  prefix,
  suffix,
  size = 'md',
  className,
}) => {
  const classes = ['uds-statistic', `uds-statistic--${size}`, className].filter(Boolean).join(' ');
  return (
    <div className={classes}>
      {label && <span className="uds-statistic__label">{label}</span>}
      <div className="uds-statistic__value">
        {prefix && <span className="uds-statistic__prefix">{prefix}</span>}
        <span className="uds-statistic__number">{value}</span>
        {suffix && <span className="uds-statistic__suffix">{suffix}</span>}
      </div>
    </div>
  );
};

Statistic.displayName = 'Statistic';

// packages/svelte/src/components/Statistic.svelte
<script lang="ts">
  interface Props {
    value: string | number;
    label?: string;
    prefix?: import('svelte').Snippet;
    suffix?: import('svelte').Snippet;
    size?: 'sm' | 'md' | 'lg';
    class?: string;
    [key: string]: any;
  }

  let {
    value,
    label,
    prefix,
    suffix,
    size = 'md',
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-statistic', `uds-statistic--${size}`, className].filter(Boolean).join(' ')
  );
</script>

<div class={classes} {...rest}>
  {#if label}
    <span class="uds-statistic__label">{label}</span>
  {/if}
  <div class="uds-statistic__value">
    {#if prefix}
      <span class="uds-statistic__prefix">{@render prefix()}</span>
    {/if}
    <span class="uds-statistic__number">{value}</span>
    {#if suffix}
      <span class="uds-statistic__suffix">{@render suffix()}</span>
    {/if}
  </div>
</div>
