// packages/react/src/components/Stepper/Stepper.tsx
import React, { useCallback, useState } from 'react';

export interface StepperStep {
  id: string;
  label: string;
  optional?: boolean;
}

export interface StepperProps {
  /** Step definitions. */
  steps: StepperStep[];
  /** Current active step index (controlled). */
  activeStep?: number;
  /** Initial active step when uncontrolled. @default 0 */
  defaultActiveStep?: number;
  /** Layout direction. @default 'horizontal' */
  orientation?: 'horizontal' | 'vertical';
  /** When true, steps are sequential (can't skip). @default true */
  linear?: boolean;
  /** Callback when a step is clicked (for non-linear). */
  onStepClick?: (index: number) => void;
  /** Called when active step changes. */
  onChange?: (index: number) => void;
  /** Additional CSS class for the root. */
  className?: string;
}

export const Stepper: React.FC<StepperProps> = ({
  steps,
  activeStep: controlledActiveStep,
  defaultActiveStep = 0,
  orientation = 'horizontal',
  linear = true,
  onStepClick,
  onChange,
  className,
}) => {
  const [internalStep, setInternalStep] = useState(defaultActiveStep);
  const activeStep = controlledActiveStep ?? internalStep;

  const handleStepClick = useCallback(
    (index: number) => {
      if (linear && index > activeStep) return;
      if (controlledActiveStep === undefined) setInternalStep(index);
      onChange?.(index);
      onStepClick?.(index);
    },
    [activeStep, linear, controlledActiveStep, onChange, onStepClick],
  );

  const classes = [
    'uds-stepper',
    `uds-stepper--${orientation}`,
    className,
  ]
    .filter(Boolean)
    .join(' ');

  return (
    <nav className={classes} aria-label="Progress">
      {steps.map((step, index) => {
        const isCompleted = index < activeStep;
        const isCurrent = index === activeStep;
        const isPending = index > activeStep;
        const isClickable = !linear || index <= activeStep;

        return (
          <React.Fragment key={step.id}>
            <div
              className={[
                'uds-stepper__step',
                isCompleted && 'uds-stepper__step--completed',
                isCurrent && 'uds-stepper__step--active',
                isPending && 'uds-stepper__step--pending',
              ]
                .filter(Boolean)
                .join(' ')}
              aria-current={isCurrent ? 'step' : undefined}
              aria-disabled={isPending && linear ? 'true' : undefined}
              role="button"
              tabIndex={isClickable ? 0 : -1}
              onClick={() => isClickable && handleStepClick(index)}
              onKeyDown={(e) => {
                if (!isClickable) return;
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  handleStepClick(index);
                }
              }}
            >
              <span className="uds-stepper__step-indicator">
                {isCompleted ? (
                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true">
                    <path d="M20 6L9 17l-5-5" />
                  </svg>
                ) : (
                  index + 1
                )}
              </span>
              <span className="uds-stepper__step-label">{step.label}</span>
              {step.optional && (
                <span className="uds-stepper__step-optional">(optional)</span>
              )}
            </div>
            {index < steps.length - 1 && (
              <span
                className={[
                  'uds-stepper__connector',
                  isCompleted && 'uds-stepper__connector--completed',
                ]
                  .filter(Boolean)
                  .join(' ')}
                aria-hidden="true"
              />
            )}
          </React.Fragment>
        );
      })}
    </nav>
  );
};

Stepper.displayName = 'Stepper';

// packages/svelte/src/components/Stepper.svelte
<script lang="ts">
  export interface StepperStep {
    id: string;
    label: string;
    optional?: boolean;
  }

  interface Props {
    steps: StepperStep[];
    activeStep?: number;
    defaultActiveStep?: number;
    orientation?: 'horizontal' | 'vertical';
    linear?: boolean;
    onStepClick?: (index: number) => void;
    onChange?: (index: number) => void;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let {
    steps,
    activeStep: controlledStep,
    defaultActiveStep = 0,
    orientation = 'horizontal',
    linear = true,
    onStepClick,
    onChange,
    class: className = '',
    ...rest
  }: Props = $props();

  let internalStep = $state(defaultActiveStep);
  let activeStep = $derived(controlledStep ?? internalStep);

  let classes = $derived(
    ['uds-stepper', `uds-stepper--${orientation}`, className].filter(Boolean).join(' ')
  );

  function handleStepClick(index: number) {
    if (linear && index > activeStep) return;
    if (controlledStep === undefined) internalStep = index;
    onChange?.(index);
    onStepClick?.(index);
  }
</script>

<nav class={classes} aria-label="Progress" {...rest}>
  {#each steps as step, index}
    <div
      class="uds-stepper__step uds-stepper__step--{index < activeStep ? 'completed' : index === activeStep ? 'active' : 'pending'}"
      aria-current={index === activeStep ? 'step' : undefined}
      aria-disabled={index > activeStep && linear ? 'true' : undefined}
      role="button"
      tabindex={!linear || index <= activeStep ? 0 : -1}
      onclick={() => (!linear || index <= activeStep) && handleStepClick(index)}
      onkeydown={(e) => (e.key === 'Enter' || e.key === ' ') && (!linear || index <= activeStep) && (e.preventDefault(), handleStepClick(index))}
    >
      <span class="uds-stepper__step-indicator">
        {#if index < activeStep}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M20 6L9 17l-5-5" /></svg>
        {:else}
          {index + 1}
        {/if}
      </span>
      <span class="uds-stepper__step-label">{step.label}</span>
      {#if step.optional}<span class="uds-stepper__step-optional">(optional)</span>{/if}
    </div>
    {#if index < steps.length - 1}
      <span class="uds-stepper__connector uds-stepper__connector--{index < activeStep ? 'completed' : ''}" aria-hidden="true"></span>
    {/if}
  {/each}
</nav>
