// packages/svelte/src/components/Toolbar.svelte
<script lang="ts">
  interface Props {
    'aria-label': string;
    orientation?: 'horizontal' | 'vertical';
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let {
    'aria-label': ariaLabel,
    orientation = 'horizontal',
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-toolbar',
      orientation === 'vertical' && 'uds-toolbar--vertical',
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );
</script>

<div class={classes} role="toolbar" aria-label={ariaLabel} {...rest}>
  {@render children?.()}
</div>

// packages/react/src/components/Toolbar/Toolbar.tsx
import type React from 'react';

export interface ToolbarProps {
  /** Toolbar content (buttons, dropdowns, etc.). */
  children: React.ReactNode;
  /** Layout direction. @default 'horizontal' */
  orientation?: 'horizontal' | 'vertical';
  /** Accessible label for the toolbar (required for screen readers). */
  'aria-label': string;
  /** Additional CSS class for the root. */
  className?: string;
}

export const Toolbar: React.FC<ToolbarProps> = ({
  children,
  orientation = 'horizontal',
  'aria-label': ariaLabel,
  className,
}) => {
  const classes = ['uds-toolbar', orientation === 'vertical' && 'uds-toolbar--vertical', className]
    .filter(Boolean)
    .join(' ');

  return (
    <div className={classes} role="toolbar" aria-label={ariaLabel}>
      {children}
    </div>
  );
};

Toolbar.displayName = 'Toolbar';
