// packages/svelte/src/components/TimePicker.svelte
<script lang="ts">
  interface Props {
    value?: string;
    size?: 'md' | 'lg';
    disabled?: boolean;
    onChange?: (v: string) => void;
    class?: string;
    [key: string]: unknown;
  }

  let {
    value = '',
    size = 'md',
    disabled = false,
    onChange,
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(['uds-time-picker', `uds-time-picker--${size}`, className].filter(Boolean).join(' '));
</script>

<input
  type="time"
  value={value}
  class={classes}
  {disabled}
  aria-label="Time"
  oninput={(e) => onChange?.((e.currentTarget as HTMLInputElement).value)}
  {...rest}
/>

// packages/react/src/components/TimePicker/TimePicker.tsx
import React from 'react';

export interface TimePickerProps extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'type' | 'value' | 'onChange' | 'size'> {
  value?: string;
  /** HH:mm format. */
  onChange?: (value: string) => void;
  size?: 'md' | 'lg';
}

export const TimePicker = React.forwardRef<HTMLInputElement, TimePickerProps>(
  ({ value = '', size = 'md', className, onChange, ...props }, ref) => {
    const classes = ['uds-time-picker', `uds-time-picker--${size}`, className].filter(Boolean).join(' ');
    return (
      <input
        ref={ref}
        type="time"
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        className={classes}
        aria-label={props['aria-label'] ?? 'Time'}
        {...props}
      />
    );
  },
);

TimePicker.displayName = 'TimePicker';
