// packages/svelte/src/components/Pagination.svelte
<script lang="ts">
  interface Props {
    variant?: 'numbered' | 'simple' | 'load-more' | 'infinite-scroll';
    size?: 'sm' | 'md';
    currentPage?: number;
    totalPages?: number;
    onPageChange?: (page: number) => void;
    class?: string;
    [key: string]: any;
  }

  let {
    variant = 'numbered',
    size = 'md',
    currentPage = 1,
    totalPages = 1,
    onPageChange,
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    [
      'uds-pagination',
      `uds-pagination--${variant}`,
      `uds-pagination--${size}`,
      className,
    ]
      .filter(Boolean)
      .join(' ')
  );

  let pages = $derived(() => {
    const p: (number | string)[] = [];
    for (let i = 1; i <= totalPages; i++) {
      if (i === 1 || i === totalPages || (i >= currentPage - 1 && i <= currentPage + 1)) {
        p.push(i);
      } else if (p[p.length - 1] !== '...') {
        p.push('...');
      }
    }
    return p;
  });

  function goTo(page: number) {
    if (page >= 1 && page <= totalPages && page !== currentPage) {
      onPageChange?.(page);
    }
  }
</script>

<nav class={classes} aria-label="Pagination" {...rest}>
  {#if variant === 'simple'}
    <button
      class="uds-pagination__prev"
      disabled={currentPage <= 1}
      onclick={() => goTo(currentPage - 1)}
      aria-label="Previous page"
    >
      Previous
    </button>
    <span class="uds-pagination__info">Page {currentPage} of {totalPages}</span>
    <button
      class="uds-pagination__next"
      disabled={currentPage >= totalPages}
      onclick={() => goTo(currentPage + 1)}
      aria-label="Next page"
    >
      Next
    </button>
  {:else if variant === 'load-more'}
    <button
      class="uds-pagination__load-more"
      disabled={currentPage >= totalPages}
      onclick={() => goTo(currentPage + 1)}
    >
      Load more
    </button>
  {:else}
    <button
      class="uds-pagination__prev"
      disabled={currentPage <= 1}
      onclick={() => goTo(currentPage - 1)}
      aria-label="Previous page"
    >
      &laquo;
    </button>
    <ol class="uds-pagination__list">
      {#each pages() as page}
        {#if typeof page === 'number'}
          <li>
            <button
              class="uds-pagination__page"
              class:uds-pagination__page--active={page === currentPage}
              aria-current={page === currentPage ? 'page' : undefined}
              onclick={() => goTo(page)}
            >
              {page}
            </button>
          </li>
        {:else}
          <li class="uds-pagination__ellipsis" aria-hidden="true">&hellip;</li>
        {/if}
      {/each}
    </ol>
    <button
      class="uds-pagination__next"
      disabled={currentPage >= totalPages}
      onclick={() => goTo(currentPage + 1)}
      aria-label="Next page"
    >
      &raquo;
    </button>
  {/if}
</nav>

// packages/react/src/components/Pagination/Pagination.tsx
import React, { useCallback } from 'react';

export interface PaginationProps extends React.HTMLAttributes<HTMLElement> {
  variant?: 'numbered' | 'simple' | 'load-more' | 'infinite-scroll';
  size?: 'sm' | 'md';
  currentPage: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

export const Pagination = React.forwardRef<HTMLElement, PaginationProps>(
  ({ variant = 'numbered', size = 'md', currentPage, totalPages, onPageChange, className, ...props }, ref) => {
    const handlePrev = useCallback(() => {
      if (currentPage > 1) onPageChange(currentPage - 1);
    }, [currentPage, onPageChange]);

    const handleNext = useCallback(() => {
      if (currentPage < totalPages) onPageChange(currentPage + 1);
    }, [currentPage, totalPages, onPageChange]);

    const classes = [
      'uds-pagination',
      `uds-pagination--${variant}`,
      `uds-pagination--${size}`,
      className,
    ].filter(Boolean).join(' ');

    if (variant === 'load-more') {
      return (
        <nav ref={ref} className={classes} aria-label="Pagination" {...props}>
          <button
            className="uds-pagination__load-more"
            onClick={handleNext}
            disabled={currentPage >= totalPages}
            type="button"
          >
            Load more
          </button>
        </nav>
      );
    }

    if (variant === 'simple') {
      return (
        <nav ref={ref} className={classes} aria-label="Pagination" {...props}>
          <button className="uds-pagination__prev" onClick={handlePrev} disabled={currentPage <= 1} aria-label="Previous page" type="button">
            Previous
          </button>
          <span className="uds-pagination__info">
            Page {currentPage} of {totalPages}
          </span>
          <button className="uds-pagination__next" onClick={handleNext} disabled={currentPage >= totalPages} aria-label="Next page" type="button">
            Next
          </button>
        </nav>
      );
    }

    const getPageNumbers = (): (number | '...')[] => {
      const pages: (number | '...')[] = [];
      const delta = 1;
      const left = Math.max(2, currentPage - delta);
      const right = Math.min(totalPages - 1, currentPage + delta);

      pages.push(1);
      if (left > 2) pages.push('...');
      for (let i = left; i <= right; i++) pages.push(i);
      if (right < totalPages - 1) pages.push('...');
      if (totalPages > 1) pages.push(totalPages);
      return pages;
    };

    return (
      <nav ref={ref} className={classes} aria-label="Pagination" {...props}>
        <button className="uds-pagination__prev" onClick={handlePrev} disabled={currentPage <= 1} aria-label="Previous page" type="button">
          Previous
        </button>
        <ol className="uds-pagination__list">
          {getPageNumbers().map((page, i) =>
            page === '...' ? (
              <li key={`ellipsis-${i}`} className="uds-pagination__ellipsis" aria-hidden="true">...</li>
            ) : (
              <li key={page}>
                <button
                  className={['uds-pagination__page', page === currentPage && 'uds-pagination__page--active'].filter(Boolean).join(' ')}
                  onClick={() => onPageChange(page)}
                  aria-current={page === currentPage ? 'page' : undefined}
                  aria-label={`Page ${page}`}
                  type="button"
                >
                  {page}
                </button>
              </li>
            )
          )}
        </ol>
        <button className="uds-pagination__next" onClick={handleNext} disabled={currentPage >= totalPages} aria-label="Next page" type="button">
          Next
        </button>
      </nav>
    );
  }
);

Pagination.displayName = 'Pagination';
