// packages/svelte/src/components/Timeline.svelte
<script lang="ts">
  interface TimelineItem {
    title: string;
    content?: string;
    time?: string;
  }

  interface Props {
    items: TimelineItem[];
    class?: string;
    [key: string]: any;
  }

  let {
    items,
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-timeline', className].filter(Boolean).join(' ')
  );
</script>

<ul class={classes} {...rest}>
  {#each items as item, i (item.title ?? `timeline-${i}`)}
    <li class="uds-timeline__item">
      <div class="uds-timeline__dot" aria-hidden="true"></div>
      <div class="uds-timeline__content">
        <div class="uds-timeline__title">{item.title}</div>
        {#if item.time}
          <time class="uds-timeline__time">{item.time}</time>
        {/if}
        {#if item.content}
          <div class="uds-timeline__body">{item.content}</div>
        {/if}
      </div>
    </li>
  {/each}
</ul>

// packages/react/src/components/Timeline/Timeline.tsx
import type React from 'react';

export interface TimelineItem {
  title: React.ReactNode;
  content?: React.ReactNode;
  time?: string;
}

export interface TimelineProps {
  items: TimelineItem[];
  className?: string;
}

export const Timeline: React.FC<TimelineProps> = ({ items, className }) => {
  const classes = ['uds-timeline', className].filter(Boolean).join(' ');
  return (
    <ul className={classes}>
      {items.map((item, i) => (
        <li
          key={typeof item.title === 'string' ? item.title : `timeline-${i}`}
          className="uds-timeline__item"
        >
          <div className="uds-timeline__dot" aria-hidden />
          <div className="uds-timeline__content">
            <div className="uds-timeline__title">{item.title}</div>
            {item.time && <time className="uds-timeline__time">{item.time}</time>}
            {item.content && <div className="uds-timeline__body">{item.content}</div>}
          </div>
        </li>
      ))}
    </ul>
  );
};

Timeline.displayName = 'Timeline';
