// packages/svelte/src/components/FormSection.svelte
<script lang="ts">
  interface Props {
    /** Section heading (e.g. "Contact details", "Payment"). */
    title: string;
    /** Optional description shown below the title. */
    description?: string;
    /** Heading level for the title. @default 2 */
    titleLevel?: 1 | 2 | 3 | 4 | 5 | 6;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: any;
  }

  let {
    title,
    description,
    titleLevel = 2,
    class: className = '',
    children,
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-form-section', className].filter(Boolean).join(' ')
  );
</script>

<div class={classes} {...rest}>
  {#if titleLevel === 1}
    <h1 class="uds-form-section__title">{title}</h1>
  {:else if titleLevel === 2}
    <h2 class="uds-form-section__title">{title}</h2>
  {:else if titleLevel === 3}
    <h3 class="uds-form-section__title">{title}</h3>
  {:else if titleLevel === 4}
    <h4 class="uds-form-section__title">{title}</h4>
  {:else if titleLevel === 5}
    <h5 class="uds-form-section__title">{title}</h5>
  {:else}
    <h6 class="uds-form-section__title">{title}</h6>
  {/if}
  {#if description}
    <p class="uds-form-section__description">{description}</p>
  {/if}
  {#if children}
    <div class="uds-form-section__fields">
      {@render children()}
    </div>
  {/if}
</div>

// packages/react/src/components/FormSection/FormSection.tsx
import React from 'react';

export interface FormSectionProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Section heading (e.g. "Contact details", "Payment"). */
  title: string;
  /** Optional description shown below the title. */
  description?: string;
  /** Heading level for the title. @default 2 */
  titleLevel?: 1 | 2 | 3 | 4 | 5 | 6;
  /** Content (form fields) grouped under this section. */
  children?: React.ReactNode;
}

/**
 * A form section or field group: heading + optional description + spacing for grouped fields.
 * Use for consistent structure on form pages (e.g. ATS, settings, multi-step forms).
 *
 * Uses BEM class `uds-form-section` with `__title` and `__description`.
 */
export const FormSection = React.forwardRef<HTMLDivElement, FormSectionProps>(
  ({ title, description, titleLevel = 2, className, children, ...props }, ref) => {
    const TitleTag = `h${titleLevel}` as React.ElementType;
    const classes = ['uds-form-section', className].filter(Boolean).join(' ');
    return (
      <div ref={ref} className={classes} {...props}>
        <TitleTag className="uds-form-section__title">{title}</TitleTag>
        {description && <p className="uds-form-section__description">{description}</p>}
        {children && <div className="uds-form-section__fields">{children}</div>}
      </div>
    );
  },
);

FormSection.displayName = 'FormSection';
