// packages/svelte/src/components/Container.svelte
<script lang="ts">
  interface Props {
    size?: 'sm' | 'md' | 'lg' | 'full';
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let { size = 'lg', class: className = '', children, ...rest }: Props = $props();

  let classes = $derived(['uds-container', `uds-container--${size}`, className].filter(Boolean).join(' '));
</script>

<div class={classes} {...rest}>
  {@render children?.()}
</div>

// packages/react/src/components/Container/Container.tsx
import React from 'react';

export interface ContainerProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Max-width size. @default 'lg' */
  size?: 'sm' | 'md' | 'lg' | 'full';
}

export const Container = React.forwardRef<HTMLDivElement, ContainerProps>(
  ({ size = 'lg', className, children, ...props }, ref) => {
    const classes = ['uds-container', `uds-container--${size}`, className].filter(Boolean).join(' ');
    return (
      <div ref={ref} className={classes} {...props}>
        {children}
      </div>
    );
  },
);

Container.displayName = 'Container';
