// packages/svelte/src/components/Typography.svelte
<script lang="ts">
  type Variant = 'h1' | 'h2' | 'h3' | 'body' | 'caption' | 'code';

  interface Props {
    variant?: Variant;
    as?: string;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let { variant = 'body', as, class: className = '', children, ...rest }: Props = $props();

  const tagMap: Record<Variant, string> = {
    h1: 'h1',
    h2: 'h2',
    h3: 'h3',
    body: 'p',
    caption: 'span',
    code: 'code',
  };
  let tag = $derived(as ?? tagMap[variant]);

  let classes = $derived(
    ['uds-typography', `uds-typography--${variant}`, className].filter(Boolean).join(' ')
  );
</script>

<svelte:element this={tag} class={classes} {...rest}>
  {@render children?.()}
</svelte:element>

// packages/react/src/components/Typography/Typography.tsx
import React from 'react';

export type TypographyVariant = 'h1' | 'h2' | 'h3' | 'body' | 'caption' | 'code';

export interface TypographyProps extends React.HTMLAttributes<HTMLElement> {
  /** Visual variant. @default 'body' */
  variant?: TypographyVariant;
}

const defaultTag: Record<TypographyVariant, 'h1' | 'h2' | 'h3' | 'p' | 'span' | 'code'> = {
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  body: 'p',
  caption: 'span',
  code: 'code',
};

export const Typography = React.forwardRef<HTMLElement, TypographyProps>(
  ({ variant = 'body', className, children, ...props }, ref) => {
    const Tag = defaultTag[variant];
    const classes = ['uds-typography', `uds-typography--${variant}`, className]
      .filter(Boolean)
      .join(' ');
    return React.createElement(
      Tag,
      { ref, className: classes, ...props },
      children,
    ) as React.ReactElement;
  },
);

Typography.displayName = 'Typography';
