// packages/svelte/src/components/Anchor.svelte
<script lang="ts">
  interface AnchorItem {
    href: string;
    title: string;
  }

  interface Props {
    items: AnchorItem[];
    smoothScroll?: boolean;
    class?: string;
    [key: string]: any;
  }

  let {
    items,
    smoothScroll = true,
    class: className = '',
    ...rest
  }: Props = $props();

  let classes = $derived(
    ['uds-anchor', className].filter(Boolean).join(' ')
  );
</script>

<nav class={classes} aria-label="On this page" {...rest}>
  <ul style:list-style="none" style:padding="0" style:margin="0">
    {#each items as item (item.href)}
      <li>
        <a
          href={item.href}
          style:scroll-behavior={smoothScroll ? 'smooth' : undefined}
          class="uds-anchor__link"
        >
          {item.title}
        </a>
      </li>
    {/each}
  </ul>
</nav>

// packages/react/src/components/Anchor/Anchor.tsx
import React from 'react';

export interface AnchorItem {
  href: string;
  title: string;
}

export interface AnchorProps {
  items: AnchorItem[];
  smoothScroll?: boolean;
  className?: string;
}

export const Anchor: React.FC<AnchorProps> = ({ items, smoothScroll = true, className }) => {
  const classes = ['uds-anchor', className].filter(Boolean).join(' ');
  return (
    <nav className={classes} aria-label="On this page">
      <ul style={{ listStyle: 'none', padding: 0, margin: 0 }}>
        {items.map((item, i) => (
          <li key={i}>
            <a
              href={item.href}
              style={smoothScroll ? { scrollBehavior: 'smooth' } : undefined}
              className="uds-anchor__link"
            >
              {item.title}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
};

Anchor.displayName = 'Anchor';
