// packages/svelte/src/components/Box.svelte
<script lang="ts">
  interface Props {
    padding?: string | number;
    margin?: string | number;
    class?: string;
    children?: import('svelte').Snippet;
    [key: string]: unknown;
  }

  let { padding, margin, class: className = '', children, ...rest }: Props = $props();

  let classes = $derived(['uds-box', className].filter(Boolean).join(' '));

  let styleObj = $derived.by(() => {
    const s: Record<string, string> = {};
    if (padding != null)
      s.padding = typeof padding === 'number' ? `${padding}px` : `var(--space-${padding}, ${padding})`;
    if (margin != null)
      s.margin = typeof margin === 'number' ? `${margin}px` : `var(--space-${margin}, ${margin})`;
    return s;
  });
</script>

<div class={classes} style={Object.keys(styleObj).length ? styleObj : undefined} {...rest}>
  {@render children?.()}
</div>

// packages/react/src/components/Box/Box.tsx
import React from 'react';

export interface BoxProps extends React.HTMLAttributes<HTMLDivElement> {
  /** Padding (space token name or number). */
  padding?: string | number;
  /** Margin (space token name or number). */
  margin?: string | number;
}

export const Box = React.forwardRef<HTMLDivElement, BoxProps>(
  ({ padding, margin, className, style, ...props }, ref) => {
    const resolvedStyle: React.CSSProperties = {
      ...style,
      ...(padding != null && {
        padding:
          typeof padding === 'number' ? `${padding}px` : `var(--space-${padding}, ${padding})`,
      }),
      ...(margin != null && {
        margin: typeof margin === 'number' ? `${margin}px` : `var(--space-${margin}, ${margin})`,
      }),
    };
    const classes = ['uds-box', className].filter(Boolean).join(' ');
    return <div ref={ref} className={classes} style={resolvedStyle} {...props} />;
  },
);

Box.displayName = 'Box';
