// packages/svelte/src/components/Image.svelte
<script lang="ts">
  interface Props {
    src?: string;
    alt: string;
    fallback?: import('svelte').Snippet;
    class?: string;
    [key: string]: any;
  }

  let {
    src,
    alt,
    fallback,
    class: className = '',
    ...rest
  }: Props = $props();

  let errored = $state(false);

  let classes = $derived(
    ['uds-image', className].filter(Boolean).join(' ')
  );

  function handleError() {
    errored = true;
  }
</script>

{#if errored && fallback}
  <div class={classes}>
    {@render fallback()}
  </div>
{:else}
  <img {src} {alt} class={classes} loading="lazy" onerror={handleError} {...rest} />
{/if}

// packages/react/src/components/Image/Image.tsx
import React from 'react';

export interface ImageProps extends React.ImgHTMLAttributes<HTMLImageElement> {
  fallback?: React.ReactNode;
  alt: string;
}

export const Image: React.FC<ImageProps> = ({ src, alt, fallback, className, onError, ...props }) => {
  const [errored, setErrored] = React.useState(false);
  const handleError = (e: React.SyntheticEvent<HTMLImageElement>) => {
    setErrored(true);
    onError?.(e);
  };
  const classes = ['uds-image', className].filter(Boolean).join(' ');
  if (errored && fallback) return <div className={classes}>{fallback}</div>;
  return (
    <img
      src={src}
      alt={alt}
      className={classes}
      loading="lazy"
      onError={handleError}
      {...props}
    />
  );
};

Image.displayName = 'Image';
